"""Create user table

Revision ID: db4c7c8a96b3
Revises: 
Create Date: 2022-01-01 19:47:14.866945

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db4c7c8a96b3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
